replicas: 1

env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-exporter
      key: CF_API_TOKEN

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi

service:
  port: 9178

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

prometheus:
  enabled: true
  interval: 1h
  scrapeTimeout: 1h