name: "Deploy to staging"

on: push

env:
  GKE_KEY: ${{ secrets.GKE_DEVELOP_KEY }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MOS_EU_GITHUB_TOKEN: ${{ secrets.MOS_EU_GITHUB_TOKEN }}
  MOS_EU_GITHUB_USERNAME: ${{ secrets.MOS_EU_GITHUB_USERNAME }}

  PROJECT_NAME: cloudflare-exporter
  APP_ENV: stage
  NAMESPACE: infra

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checking out Pablo
      uses: actions/checkout@v2
      with:
        repository: MyOnlineStore/pablo
        ref: v2
        token: ${{ secrets.MOS_EU_GITHUB_TOKEN }}
        path: .github/actions/pablo

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GKE_DEVELOP_KEY }}
        export_default_credentials: true

    # Build the Docker image
    - name: Build and Push Image
      id: dockerBuild
      uses: ./.github/actions/pablo
      with:
        command: docker.build-and-push

    outputs:
      imageHash: ${{ steps.dockerBuild.outputs.imageHash }}
      imageTag: ${{ steps.dockerBuild.outputs.imageTag }}

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checking out Pablo
      uses: actions/checkout@v2
      with:
        repository: MyOnlineStore/pablo
        ref: v2
        token: ${{ secrets.MOS_EU_GITHUB_TOKEN }}
        path: .github/actions/pablo

    # Deploy
    - name: Deploy
      uses: ./.github/actions/pablo
      with:
        command: kubernetes.rolling-deployment
        helmChart: deployment
        helmVersion: '0'
        imageHash: ${{ needs.build.outputs.imageHash }}
        imageTag: ${{ needs.build.outputs.imageTag }}

